# Generated by Django 6.0.1 on 2026-02-01 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_wash', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена мойки')),
            ],
            options={
                'verbose_name': 'Цена на мойку',
                'verbose_name_plural': 'Цены на мойку',
            },
        ),
        migrations.CreateModel(
            name='BookCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('duration_start', models.DateField(auto_now=True, verbose_name='Дата начало')),
                ('duration_end', models.DateField(auto_now=True, verbose_name='Дата конец')),
                ('child_seat', models.BooleanField(default=True, verbose_name='Детское кресло')),
                ('is_wish', models.BooleanField(default=True, verbose_name='Мойка')),
                ('car_delivery', models.BooleanField(default=True, verbose_name='Подача авто')),
                ('call_time', models.TimeField(auto_now=True, verbose_name='Время вызова')),
                ('is_city', models.BooleanField(default=False, verbose_name='Город')),
                ('is_airport', models.BooleanField(default=True, verbose_name='Аэропорт')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая цена')),
                ('has_wish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carwashoption', verbose_name='Цена мойки')),
            ],
            options={
                'verbose_name': 'Бронирование машины',
                'verbose_name_plural': 'Бронирование машин',
            },
        ),
    ]
