# Generated by Django 6.0.1 on 2026-02-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('img', models.ImageField(upload_to='img_car/', verbose_name='Изображение')),
                ('brand', models.CharField(max_length=150, verbose_name='Марка')),
                ('model', models.CharField(max_length=150, verbose_name='Модель')),
                ('seating', models.PositiveIntegerField(default=0, verbose_name='Посадочные места')),
                ('engine_power', models.FloatField(verbose_name='Мощность двигателя')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ'), ('electric', 'Электрический'), ('hybrid', 'Гибрид')], default='petrol', verbose_name='Вид топлива')),
                ('body_car', models.CharField(max_length=150, verbose_name='Кузов')),
                ('year_of_manufacture', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('duration_start', models.DateField(verbose_name='Дата начало')),
                ('duration_end', models.DateField(verbose_name='Дата конец')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка (%)')),
                ('pledge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Залог')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='CarWashOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_wash', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена мойки')),
            ],
            options={
                'verbose_name': 'Цена на мойку',
                'verbose_name_plural': 'Цены на мойку',
            },
        ),
        migrations.CreateModel(
            name='BookCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_seat', models.BooleanField(default=False, verbose_name='Детское кресло')),
                ('is_wish', models.BooleanField(default=True, verbose_name='Нужна мойка')),
                ('car_delivery', models.BooleanField(default=False, verbose_name='Подача авто')),
                ('call_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания заявки')),
                ('is_city', models.BooleanField(default=True, verbose_name='По городу')),
                ('is_airport', models.BooleanField(default=False, verbose_name='В аэропорт')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='car.car', verbose_name='Машина')),
                ('has_wash_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.carwashoption', verbose_name='Тип мойки')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
