# Generated by Django 6.0.1 on 2026-02-08 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('img', models.ImageField(upload_to='img_car/', verbose_name='Изображение')),
                ('brand', models.CharField(max_length=150, verbose_name='Марка')),
                ('model', models.CharField(max_length=150, verbose_name='Модель')),
                ('seating', models.PositiveIntegerField(default=0, verbose_name='Посадочные места')),
                ('engine_power', models.FloatField(verbose_name='Мощность двигателя')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('drive_unit', models.CharField(blank=True, max_length=50, verbose_name='Привод')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ'), ('electric', 'Электрический'), ('hybrid', 'Гибрид')], default='petrol', verbose_name='Вид топлива')),
                ('body_car', models.CharField(max_length=150, verbose_name='Кузов')),
                ('duration_start', models.DateField(verbose_name='Дата начала')),
                ('duration_end', models.DateField(verbose_name='Дата конца')),
                ('year_of_manufacture', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка (%)')),
                ('pledge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Залог')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='CarWashOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_wash', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена мойки')),
            ],
        ),
        migrations.CreateModel(
            name='BookCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_start', models.DateField(verbose_name='Дата начала')),
                ('duration_end', models.DateField(verbose_name='Дата конца')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_price_snapshot', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Итоговая цена')),
                ('child_seat', models.BooleanField(default=False, verbose_name='Детское кресло')),
                ('is_wish', models.BooleanField(default=True, verbose_name='Нужна мойка')),
                ('car_delivery', models.BooleanField(default=False, verbose_name='Подача авто')),
                ('call_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания заявки')),
                ('is_city', models.BooleanField(blank=True, default=True, null=True, verbose_name='По городу')),
                ('is_airport', models.BooleanField(blank=True, default=False, null=True, verbose_name='В аэропорт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='car.car', verbose_name='Машина')),
                ('has_wash_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.carwashoption', verbose_name='Тип мойки')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('agreement', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='car.bookcar', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Данные клиента',
                'verbose_name_plural': 'Данные клиентов',
            },
        ),
    ]
