# Generated by Django 6.0.1 on 2026-02-14 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('img', models.ImageField(upload_to='base_location_img/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Базовая локация',
                'verbose_name_plural': 'Базовые локации',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('base_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.baselocation', verbose_name='Базовая локация')),
                ('cars', models.ManyToManyField(related_name='locations', to='car.car', verbose_name='Доступные машины')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='ImgLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='location_img/', verbose_name='Изображение')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Изображение локации',
                'verbose_name_plural': 'Изображения локации',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('parameter', models.CharField(max_length=100, verbose_name='Параметры')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='location.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
    ]
