# Generated by Django 6.0.1 on 2026-02-08 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Лимит цены')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('is_per_day', models.BooleanField(default=False, verbose_name='Расчет посуточно')),
            ],
            options={
                'verbose_name': 'Доп. услуга',
                'verbose_name_plural': 'Доп. услуги',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_from', models.PositiveSmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=1, verbose_name='С (месяц)')),
                ('month_to', models.PositiveSmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=1, verbose_name='По (месяц)')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_day', models.PositiveIntegerField(verbose_name='Дней от')),
                ('max_day', models.PositiveIntegerField(blank=True, null=True, verbose_name='Дней до')),
                ('price_period', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость (в сутки)')),
                ('is_active', models.BooleanField(default=True, verbose_name='План активен')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='car.car', verbose_name='Машина')),
                ('extra_service', models.ManyToManyField(blank=True, to='price.extraservice', verbose_name='Включенные услуги')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='price.season', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ['car', 'min_day'],
            },
        ),
    ]
